-- Blackwell technology transmission demo v1 import
-- Generated by scripts/generated/build_blackwell_demo_v1.mjs
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

-- Object instances: 公司
CREATE TABLE IF NOT EXISTS `company` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `company`
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `company` (`unique_id`, `name`, `description`, `source_url`) VALUES
('obj_company_nvidia', 'NVIDIA Corporation', 'GPU and accelerated computing platform supplier.', 'https://www.nvidia.com/en-us/data-center/technologies/blackwell-architecture/'),
('obj_company_tsmc', 'Taiwan Semiconductor Manufacturing Company Limited', 'Foundry and advanced packaging provider for CoWoS/3DFabric.', 'https://3dfabric.tsmc.com/english/dedicatedFoundry/technology/cowos.htm'),
('obj_company_skhynix', 'SK hynix Inc.', 'Memory supplier with HBM3E products.', 'https://news.skhynix.com/sk-hynix-begins-volume-production-of-industrys-first-hbm3e/'),
('obj_company_micron', 'Micron Technology Inc.', 'Memory supplier with HBM3E products.', 'https://www.micron.com/products/memory/hbm/hbm3e'),
('obj_company_samsung', 'Samsung Electronics Co. Ltd.', 'Memory supplier with HBM3E products.', 'https://semiconductor.samsung.com/dram/hbm/hbm3e/'),
('obj_company_ibiden', 'Ibiden Co., Ltd.', 'IC package substrate supplier.', 'https://www.ibiden.com/product/electronics/package_substrate/'),
('obj_company_unimicron', 'Unimicron Technology Corporation', 'IC substrate supplier.', 'https://www.unimicron.com/en/product/IC-Substrate'),
('obj_company_shinko', 'Shinko Electric Industries Co., Ltd.', 'Semiconductor package supplier.', 'https://www.shinko.co.jp/english/product/package/'),
('obj_company_besi', 'BE Semiconductor Industries N.V.', 'Advanced packaging equipment supplier.', 'https://www.besi.com/products/advanced-packaging/'),
('obj_company_asmpt', 'ASMPT Limited', 'Advanced packaging and semiconductor assembly equipment supplier.', 'https://www.asmpt.com/en/products/semiconductor-solutions/advanced-packaging'),
('obj_company_kulicke', 'Kulicke and Soffa Industries, Inc.', 'Advanced packaging equipment supplier.', 'https://www.kns.com/Products/Advanced-Packaging'),
('obj_company_disco', 'DISCO Corporation', 'Wafer grinding and thinning equipment supplier.', 'https://www.disco.co.jp/eg/products/grinder/')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: GPU
CREATE TABLE IF NOT EXISTS `graphics_processing_unit` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `graphics_processing_unit`
  ADD COLUMN IF NOT EXISTS `architecture_generation` text NULL,
  ADD COLUMN IF NOT EXISTS `compute_die_count` text NULL,
  ADD COLUMN IF NOT EXISTS `process_platform` text NULL,
  ADD COLUMN IF NOT EXISTS `hbm_generation` text NULL,
  ADD COLUMN IF NOT EXISTS `hbm_capacity_gb` text NULL,
  ADD COLUMN IF NOT EXISTS `hbm_bandwidth_tbps` text NULL,
  ADD COLUMN IF NOT EXISTS `packaging_solution` text NULL,
  ADD COLUMN IF NOT EXISTS `target_application` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `graphics_processing_unit` (`unique_id`, `name`, `description`, `architecture_generation`, `compute_die_count`, `process_platform`, `hbm_generation`, `hbm_capacity_gb`, `hbm_bandwidth_tbps`, `packaging_solution`, `target_application`, `transmission_role`, `source_url`) VALUES
('obj_gpu_nvidia_b200', 'NVIDIA B200 Tensor Core GPU', '核心产品实例，承接双计算芯粒、HBM3E、先进封装需求', 'NVIDIA Blackwell Architecture', '2', 'TSMC 4NP', 'HBM3E', '192', '8', 'TSMC CoWoS-L', 'AI training and inference', '核心产品实例，承接双计算芯粒、HBM3E、先进封装需求', 'https://www.nvidia.com/en-us/data-center/technologies/blackwell-architecture/')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `architecture_generation`=VALUES(`architecture_generation`), `compute_die_count`=VALUES(`compute_die_count`), `process_platform`=VALUES(`process_platform`), `hbm_generation`=VALUES(`hbm_generation`), `hbm_capacity_gb`=VALUES(`hbm_capacity_gb`), `hbm_bandwidth_tbps`=VALUES(`hbm_bandwidth_tbps`), `packaging_solution`=VALUES(`packaging_solution`), `target_application`=VALUES(`target_application`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: 训练加速器
CREATE TABLE IF NOT EXISTS `training_accelerator` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `training_accelerator`
  ADD COLUMN IF NOT EXISTS `architecture_generation` text NULL,
  ADD COLUMN IF NOT EXISTS `gpu_count` text NULL,
  ADD COLUMN IF NOT EXISTS `cpu_configuration` text NULL,
  ADD COLUMN IF NOT EXISTS `hbm_capacity_gb` text NULL,
  ADD COLUMN IF NOT EXISTS `hbm_bandwidth_tbps` text NULL,
  ADD COLUMN IF NOT EXISTS `interconnect` text NULL,
  ADD COLUMN IF NOT EXISTS `target_workload` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `training_accelerator` (`unique_id`, `name`, `description`, `architecture_generation`, `gpu_count`, `cpu_configuration`, `hbm_capacity_gb`, `hbm_bandwidth_tbps`, `interconnect`, `target_workload`, `transmission_role`, `source_url`) VALUES
('obj_training_accelerator_gb200', 'NVIDIA GB200 Grace Blackwell Superchip', '系统级训练加速实例，连接架构、GPU、HBM与数据中心应用', 'NVIDIA Blackwell Architecture', '2', '1 Grace CPU', '372', '16', 'NVLink-C2C / NVLink', 'AI training and trillion-parameter inference', '系统级训练加速实例，连接架构、GPU、HBM与数据中心应用', 'https://www.nvidia.com/en-us/data-center/gb200-nvl72/')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `architecture_generation`=VALUES(`architecture_generation`), `gpu_count`=VALUES(`gpu_count`), `cpu_configuration`=VALUES(`cpu_configuration`), `hbm_capacity_gb`=VALUES(`hbm_capacity_gb`), `hbm_bandwidth_tbps`=VALUES(`hbm_bandwidth_tbps`), `interconnect`=VALUES(`interconnect`), `target_workload`=VALUES(`target_workload`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: GPU架构世代
CREATE TABLE IF NOT EXISTS `gpu_architecture_generation` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `gpu_architecture_generation`
  ADD COLUMN IF NOT EXISTS `release_date` text NULL,
  ADD COLUMN IF NOT EXISTS `compute_die_count` text NULL,
  ADD COLUMN IF NOT EXISTS `die_to_die_bandwidth_tbps` text NULL,
  ADD COLUMN IF NOT EXISTS `transistor_count_billion` text NULL,
  ADD COLUMN IF NOT EXISTS `process_platform` text NULL,
  ADD COLUMN IF NOT EXISTS `technical_bottleneck` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `gpu_architecture_generation` (`unique_id`, `name`, `description`, `release_date`, `compute_die_count`, `die_to_die_bandwidth_tbps`, `transistor_count_billion`, `process_platform`, `technical_bottleneck`, `transmission_role`, `source_url`) VALUES
('obj_gpu_arch_blackwell', 'NVIDIA Blackwell Architecture', '技术路线起点：双reticle-limited dies推动Chiplet和封装升级', '2024-03-18', '2', '10', '208', 'TSMC 4NP', 'reticle-limited die, yield, compute scaling', '技术路线起点：双reticle-limited dies推动Chiplet和封装升级', 'https://www.nvidia.com/en-us/data-center/technologies/blackwell-architecture/')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `release_date`=VALUES(`release_date`), `compute_die_count`=VALUES(`compute_die_count`), `die_to_die_bandwidth_tbps`=VALUES(`die_to_die_bandwidth_tbps`), `transistor_count_billion`=VALUES(`transistor_count_billion`), `process_platform`=VALUES(`process_platform`), `technical_bottleneck`=VALUES(`technical_bottleneck`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: HBM
CREATE TABLE IF NOT EXISTS `high_bandwidth_memory` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `high_bandwidth_memory`
  ADD COLUMN IF NOT EXISTS `generation` text NULL,
  ADD COLUMN IF NOT EXISTS `stack_height_layers` text NULL,
  ADD COLUMN IF NOT EXISTS `capacity_per_stack_gb` text NULL,
  ADD COLUMN IF NOT EXISTS `pin_speed_gbps` text NULL,
  ADD COLUMN IF NOT EXISTS `bandwidth_per_stack_tbps` text NULL,
  ADD COLUMN IF NOT EXISTS `io_width_bit` text NULL,
  ADD COLUMN IF NOT EXISTS `supplier` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `high_bandwidth_memory` (`unique_id`, `name`, `description`, `generation`, `stack_height_layers`, `capacity_per_stack_gb`, `pin_speed_gbps`, `bandwidth_per_stack_tbps`, `io_width_bit`, `supplier`, `transmission_role`, `source_url`) VALUES
('obj_hbm_skhynix_hbm3e', 'SK hynix HBM3E', '高带宽存储需求受Blackwell/GB200拉动', 'HBM3E', '12', '36', NULL, NULL, '1024', 'SK hynix', '高带宽存储需求受Blackwell/GB200拉动', 'https://news.skhynix.com/sk-hynix-begins-volume-production-of-worlds-first-12-layer-hbm3e/'),
('obj_hbm_micron_hbm3e', 'Micron HBM3E', '高带宽存储供给候选', 'HBM3E', '8', '24', '9.2', '1.2', '1024', 'Micron', '高带宽存储供给候选', 'https://www.micron.com/products/memory/hbm/hbm3e'),
('obj_hbm_samsung_hbm3e', 'Samsung HBM3E', '高带宽存储供给候选', 'HBM3E', NULL, NULL, NULL, NULL, '1024', 'Samsung Electronics', '高带宽存储供给候选', 'https://semiconductor.samsung.com/dram/hbm/hbm3e/'),
('obj_hbm_hbm3e_generic', 'HBM3E', '作为CoWoS-L适配对象的通用HBM3E实例', 'HBM3E', NULL, NULL, NULL, NULL, '1024', 'Multiple suppliers', '作为CoWoS-L适配对象的通用HBM3E实例', 'https://www.micron.com/products/memory/hbm/hbm3e')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `generation`=VALUES(`generation`), `stack_height_layers`=VALUES(`stack_height_layers`), `capacity_per_stack_gb`=VALUES(`capacity_per_stack_gb`), `pin_speed_gbps`=VALUES(`pin_speed_gbps`), `bandwidth_per_stack_tbps`=VALUES(`bandwidth_per_stack_tbps`), `io_width_bit`=VALUES(`io_width_bit`), `supplier`=VALUES(`supplier`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: HBM世代
CREATE TABLE IF NOT EXISTS `hbm_generation` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `hbm_generation`
  ADD COLUMN IF NOT EXISTS `generation_name` text NULL,
  ADD COLUMN IF NOT EXISTS `typical_stack_height` text NULL,
  ADD COLUMN IF NOT EXISTS `typical_capacity_per_stack` text NULL,
  ADD COLUMN IF NOT EXISTS `typical_bandwidth_per_stack` text NULL,
  ADD COLUMN IF NOT EXISTS `technology_significance` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `hbm_generation` (`unique_id`, `name`, `description`, `generation_name`, `typical_stack_height`, `typical_capacity_per_stack`, `typical_bandwidth_per_stack`, `technology_significance`, `source_url`) VALUES
('obj_hbm_generation_hbm3e', 'HBM3E Generation', 'AI GPU的高带宽显存代际升级', 'HBM3E', '8-high / 12-high', '24GB / 36GB', '>1.2TB/s per placement for Micron disclosed parts', 'AI GPU的高带宽显存代际升级', 'https://www.micron.com/products/memory/hbm/hbm3e')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `generation_name`=VALUES(`generation_name`), `typical_stack_height`=VALUES(`typical_stack_height`), `typical_capacity_per_stack`=VALUES(`typical_capacity_per_stack`), `typical_bandwidth_per_stack`=VALUES(`typical_bandwidth_per_stack`), `technology_significance`=VALUES(`technology_significance`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: 封装方案
CREATE TABLE IF NOT EXISTS `packaging_solution` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `packaging_solution`
  ADD COLUMN IF NOT EXISTS `technology_type` text NULL,
  ADD COLUMN IF NOT EXISTS `interposer_type` text NULL,
  ADD COLUMN IF NOT EXISTS `local_silicon_interconnect` text NULL,
  ADD COLUMN IF NOT EXISTS `multi_die_support` text NULL,
  ADD COLUMN IF NOT EXISTS `hbm_support` text NULL,
  ADD COLUMN IF NOT EXISTS `key_bottleneck` text NULL,
  ADD COLUMN IF NOT EXISTS `provider` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `packaging_solution` (`unique_id`, `name`, `description`, `technology_type`, `interposer_type`, `local_silicon_interconnect`, `multi_die_support`, `hbm_support`, `key_bottleneck`, `provider`, `transmission_role`, `source_url`) VALUES
('obj_packaging_solution_tsmc_cowos_l', 'TSMC CoWoS-L', '承接Blackwell双芯粒和HBM3E堆栈的封装方案', '2.5D advanced packaging', 'RDL-based interposer with embedded local silicon interconnect', 'LSI', 'Yes', 'HBM stacks and large HPC products', 'larger package size and high routing density', 'TSMC', '承接Blackwell双芯粒和HBM3E堆栈的封装方案', 'https://3dfabric.tsmc.com/english/dedicatedFoundry/technology/cowos.htm')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `technology_type`=VALUES(`technology_type`), `interposer_type`=VALUES(`interposer_type`), `local_silicon_interconnect`=VALUES(`local_silicon_interconnect`), `multi_die_support`=VALUES(`multi_die_support`), `hbm_support`=VALUES(`hbm_support`), `key_bottleneck`=VALUES(`key_bottleneck`), `provider`=VALUES(`provider`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: 先进封装技术
CREATE TABLE IF NOT EXISTS `advanced_packaging_technology` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `advanced_packaging_technology`
  ADD COLUMN IF NOT EXISTS `packaging_type` text NULL,
  ADD COLUMN IF NOT EXISTS `integration_dimension` text NULL,
  ADD COLUMN IF NOT EXISTS `max_die_count` text NULL,
  ADD COLUMN IF NOT EXISTS `interconnect_density_requirement` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `advanced_packaging_technology` (`unique_id`, `name`, `description`, `packaging_type`, `integration_dimension`, `max_die_count`, `interconnect_density_requirement`, `transmission_role`, `source_url`) VALUES
('obj_adv_packaging_chiplet_multi_die', 'Chiplet / Multi-die Integration', '把单大芯片演进为多die系统级封装', 'advanced packaging', '2.5D / multi-die', NULL, 'high', '把单大芯片演进为多die系统级封装', 'https://www.nvidia.com/en-us/data-center/technologies/blackwell-architecture/'),
('obj_adv_packaging_cowos', 'TSMC CoWoS Advanced Packaging', 'CoWoS-L的技术能力承载层', '2.5D advanced packaging', '2.5D', NULL, 'high', 'CoWoS-L的技术能力承载层', 'https://3dfabric.tsmc.com/english/dedicatedFoundry/technology/cowos.htm')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `packaging_type`=VALUES(`packaging_type`), `integration_dimension`=VALUES(`integration_dimension`), `max_die_count`=VALUES(`max_die_count`), `interconnect_density_requirement`=VALUES(`interconnect_density_requirement`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: 封装技术世代
CREATE TABLE IF NOT EXISTS `packaging_technology_generation` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `packaging_technology_generation`
  ADD COLUMN IF NOT EXISTS `generation_name` text NULL,
  ADD COLUMN IF NOT EXISTS `packaging_dimension` text NULL,
  ADD COLUMN IF NOT EXISTS `representative_technology` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `packaging_technology_generation` (`unique_id`, `name`, `description`, `generation_name`, `packaging_dimension`, `representative_technology`, `transmission_role`, `source_url`) VALUES
('obj_packaging_generation_2_5d', '2.5D Advanced Packaging Generation', '先进封装代际，连接封装技术和具体封装方案', '2.5D advanced packaging', '2.5D', 'CoWoS / CoWoS-L', '先进封装代际，连接封装技术和具体封装方案', 'https://3dfabric.tsmc.com/english/dedicatedFoundry/technology/cowos.htm')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `generation_name`=VALUES(`generation_name`), `packaging_dimension`=VALUES(`packaging_dimension`), `representative_technology`=VALUES(`representative_technology`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: 封装测试服务
CREATE TABLE IF NOT EXISTS `assembly_test_service` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `assembly_test_service`
  ADD COLUMN IF NOT EXISTS `service_type` text NULL,
  ADD COLUMN IF NOT EXISTS `supported_packaging_solution` text NULL,
  ADD COLUMN IF NOT EXISTS `supported_product` text NULL,
  ADD COLUMN IF NOT EXISTS `capacity_status` text NULL,
  ADD COLUMN IF NOT EXISTS `provider` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `assembly_test_service` (`unique_id`, `name`, `description`, `service_type`, `supported_packaging_solution`, `supported_product`, `capacity_status`, `provider`, `transmission_role`, `source_url`) VALUES
('obj_service_tsmc_cowos', 'TSMC CoWoS Advanced Packaging Service', '产能瓶颈和扩产承接环节', 'advanced packaging service', 'TSMC CoWoS-L', 'NVIDIA Blackwell GPU / AI accelerator', 'capacity expanding', 'TSMC', '产能瓶颈和扩产承接环节', 'https://3dfabric.tsmc.com/english/dedicatedFoundry/technology/cowos.htm')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `service_type`=VALUES(`service_type`), `supported_packaging_solution`=VALUES(`supported_packaging_solution`), `supported_product`=VALUES(`supported_product`), `capacity_status`=VALUES(`capacity_status`), `provider`=VALUES(`provider`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: 后道工厂
CREATE TABLE IF NOT EXISTS `backend_facility` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `backend_facility`
  ADD COLUMN IF NOT EXISTS `owner_company` text NULL,
  ADD COLUMN IF NOT EXISTS `country_region` text NULL,
  ADD COLUMN IF NOT EXISTS `city_or_site` text NULL,
  ADD COLUMN IF NOT EXISTS `facility_type` text NULL,
  ADD COLUMN IF NOT EXISTS `related_technology` text NULL,
  ADD COLUMN IF NOT EXISTS `status` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `backend_facility` (`unique_id`, `name`, `description`, `owner_company`, `country_region`, `city_or_site`, `facility_type`, `related_technology`, `status`, `transmission_role`, `source_url`) VALUES
('obj_facility_tsmc_ap6', 'TSMC Advanced Backend Fab 6 (AP6)', 'CoWoS扩产的设施承接对象', 'TSMC', 'Taiwan', 'Zhunan', 'advanced backend fab', '3DFabric / CoWoS', 'operational / expansion referenced publicly', 'CoWoS扩产的设施承接对象', 'https://en.wikipedia.org/wiki/TSMC')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `owner_company`=VALUES(`owner_company`), `country_region`=VALUES(`country_region`), `city_or_site`=VALUES(`city_or_site`), `facility_type`=VALUES(`facility_type`), `related_technology`=VALUES(`related_technology`), `status`=VALUES(`status`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: ABF载板
CREATE TABLE IF NOT EXISTS `abf_substrate` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `abf_substrate`
  ADD COLUMN IF NOT EXISTS `dielectric_material` text NULL,
  ADD COLUMN IF NOT EXISTS `target_application` text NULL,
  ADD COLUMN IF NOT EXISTS `supplier` text NULL,
  ADD COLUMN IF NOT EXISTS `demand_driver` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `abf_substrate` (`unique_id`, `name`, `description`, `dielectric_material`, `target_application`, `supplier`, `demand_driver`, `transmission_role`, `source_url`) VALUES
('obj_abf_substrate', 'ABF Substrate', 'CoWoS-L后续带动的封装基板需求', 'ABF build-up film', 'HPC GPU / AI accelerator packaging', 'Ibiden / Unimicron / Shinko', 'large package and high-density interconnect', 'CoWoS-L后续带动的封装基板需求', 'https://www.ibiden.com/product/electronics/package_substrate/')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `dielectric_material`=VALUES(`dielectric_material`), `target_application`=VALUES(`target_application`), `supplier`=VALUES(`supplier`), `demand_driver`=VALUES(`demand_driver`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: 倒装键合机
CREATE TABLE IF NOT EXISTS `flip_chip_bonding_equipment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `flip_chip_bonding_equipment`
  ADD COLUMN IF NOT EXISTS `equipment_category` text NULL,
  ADD COLUMN IF NOT EXISTS `supplier` text NULL,
  ADD COLUMN IF NOT EXISTS `supported_process` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `flip_chip_bonding_equipment` (`unique_id`, `name`, `description`, `equipment_category`, `supplier`, `supported_process`, `transmission_role`, `source_url`) VALUES
('obj_equipment_flip_chip_bonder', 'Flip Chip Bonder', '先进封装贴装/键合设备需求', 'advanced packaging bonding equipment', 'BESI / ASMPT / K&S', 'flip-chip attach for advanced packaging', '先进封装贴装/键合设备需求', 'https://www.besi.com/products/advanced-packaging/')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `equipment_category`=VALUES(`equipment_category`), `supplier`=VALUES(`supplier`), `supported_process`=VALUES(`supported_process`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: 混合键合机
CREATE TABLE IF NOT EXISTS `hybrid_bonding_equipment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `hybrid_bonding_equipment`
  ADD COLUMN IF NOT EXISTS `equipment_category` text NULL,
  ADD COLUMN IF NOT EXISTS `supplier` text NULL,
  ADD COLUMN IF NOT EXISTS `supported_process` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `hybrid_bonding_equipment` (`unique_id`, `name`, `description`, `equipment_category`, `supplier`, `supported_process`, `transmission_role`, `source_url`) VALUES
('obj_equipment_hybrid_bonder', 'Hybrid Bonder', '更高互连密度下的设备候选', 'advanced bonding equipment', 'BESI / ASMPT', 'hybrid bonding / high-density interconnect', '更高互连密度下的设备候选', 'https://www.besi.com/products/advanced-packaging/')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `equipment_category`=VALUES(`equipment_category`), `supplier`=VALUES(`supplier`), `supported_process`=VALUES(`supported_process`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: 晶圆减薄机
CREATE TABLE IF NOT EXISTS `wafer_thinning_equipment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `wafer_thinning_equipment`
  ADD COLUMN IF NOT EXISTS `equipment_category` text NULL,
  ADD COLUMN IF NOT EXISTS `supplier` text NULL,
  ADD COLUMN IF NOT EXISTS `supported_process` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `wafer_thinning_equipment` (`unique_id`, `name`, `description`, `equipment_category`, `supplier`, `supported_process`, `transmission_role`, `source_url`) VALUES
('obj_equipment_wafer_thinning', 'Wafer Thinning Equipment', '先进封装前后道处理设备需求', 'back-end wafer processing equipment', 'DISCO', 'wafer thinning for advanced packaging', '先进封装前后道处理设备需求', 'https://www.disco.co.jp/eg/products/grinder/')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `equipment_category`=VALUES(`equipment_category`), `supplier`=VALUES(`supplier`), `supported_process`=VALUES(`supported_process`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: 资本开支
CREATE TABLE IF NOT EXISTS `capital_expenditure` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `capital_expenditure`
  ADD COLUMN IF NOT EXISTS `capex_amount` text NULL,
  ADD COLUMN IF NOT EXISTS `currency` text NULL,
  ADD COLUMN IF NOT EXISTS `period` text NULL,
  ADD COLUMN IF NOT EXISTS `capex_category` text NULL,
  ADD COLUMN IF NOT EXISTS `region` text NULL,
  ADD COLUMN IF NOT EXISTS `capacity_or_technology_purpose` text NULL,
  ADD COLUMN IF NOT EXISTS `company_name` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `capital_expenditure` (`unique_id`, `name`, `description`, `capex_amount`, `currency`, `period`, `capex_category`, `region`, `capacity_or_technology_purpose`, `company_name`, `transmission_role`, `source_url`) VALUES
('obj_metric_tsmc_adv_packaging_capex', 'TSMC Advanced Packaging CapEx', '扩产和设备采购的市场层观察指标', NULL, NULL, '2024-2026', 'advanced packaging capacity expansion', 'Taiwan', 'CoWoS / 3DFabric capacity', 'TSMC', '扩产和设备采购的市场层观察指标', 'https://3dfabric.tsmc.com/english/dedicatedFoundry/technology/cowos.htm')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `capex_amount`=VALUES(`capex_amount`), `currency`=VALUES(`currency`), `period`=VALUES(`period`), `capex_category`=VALUES(`capex_category`), `region`=VALUES(`region`), `capacity_or_technology_purpose`=VALUES(`capacity_or_technology_purpose`), `company_name`=VALUES(`company_name`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Object instances: 数据中心计算应用
CREATE TABLE IF NOT EXISTS `ai_server_application` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(500) DEFAULT NULL,
  `unique_id` varchar(500) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unique_id` (`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Blackwell demo instance data';
ALTER TABLE `ai_server_application`
  ADD COLUMN IF NOT EXISTS `application_scenario` text NULL,
  ADD COLUMN IF NOT EXISTS `compute_requirement` text NULL,
  ADD COLUMN IF NOT EXISTS `transmission_role` text NULL,
  ADD COLUMN IF NOT EXISTS `source_url` text NULL;
INSERT INTO `ai_server_application` (`unique_id`, `name`, `description`, `application_scenario`, `compute_requirement`, `transmission_role`, `source_url`) VALUES
('obj_app_ai_server_training', 'AI Server / Data Center AI Training', '需求端起点，解释Blackwell产品需求', 'large-scale AI training and inference', 'high GPU compute, high memory bandwidth, scale-up interconnect', '需求端起点，解释Blackwell产品需求', 'https://www.nvidia.com/en-us/data-center/gb200-nvl72/')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `description`=VALUES(`description`), `application_scenario`=VALUES(`application_scenario`), `compute_requirement`=VALUES(`compute_requirement`), `transmission_role`=VALUES(`transmission_role`), `source_url`=VALUES(`source_url`), updated_at=CURRENT_TIMESTAMP;

-- Link type additions required by this demo
INSERT INTO link_types (id, name, source_object_id, target_object_id, cardinality, link_category, description, industry_id, source_column, target_column, status, project_id, created_at, updated_at)
VALUES ('lt_gpu_architecture_generation_drives_advanced_packaging_technology', 'GPU架构世代驱动先进封装技术', 'gpu_architecture_generation', 'advanced_packaging_technology', 'M:N', '技术驱动', 'Blackwell双计算芯粒/Chiplet化驱动先进封装能力需求。', NULL, NULL, NULL, 'active', 'project_1780997325389', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE name=VALUES(name), source_object_id=VALUES(source_object_id), target_object_id=VALUES(target_object_id), link_category=VALUES(link_category), description=VALUES(description), status='active', updated_at=CURRENT_TIMESTAMP;

INSERT INTO link_types (id, name, source_object_id, target_object_id, cardinality, link_category, description, industry_id, source_column, target_column, status, project_id, created_at, updated_at)
VALUES ('lt_advanced_packaging_technology_corresponds_to_packaging_solution', '先进封装技术对应封装方案', 'advanced_packaging_technology', 'packaging_solution', 'M:N', '技术关联', '把Chiplet/2.5D技术能力落到CoWoS-L等具体封装方案。', NULL, NULL, NULL, 'active', 'project_1780997325389', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE name=VALUES(name), source_object_id=VALUES(source_object_id), target_object_id=VALUES(target_object_id), link_category=VALUES(link_category), description=VALUES(description), status='active', updated_at=CURRENT_TIMESTAMP;

INSERT INTO link_types (id, name, source_object_id, target_object_id, cardinality, link_category, description, industry_id, source_column, target_column, status, project_id, created_at, updated_at)
VALUES ('lt_graphics_processing_unit_adopts_packaging_solution', 'GPU采用封装方案', 'graphics_processing_unit', 'packaging_solution', 'M:N', '技术关联', '表达B200/Blackwell产品与CoWoS-L封装方案的实例级绑定。', NULL, NULL, NULL, 'active', 'project_1780997325389', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE name=VALUES(name), source_object_id=VALUES(source_object_id), target_object_id=VALUES(target_object_id), link_category=VALUES(link_category), description=VALUES(description), status='active', updated_at=CURRENT_TIMESTAMP;

INSERT INTO link_types (id, name, source_object_id, target_object_id, cardinality, link_category, description, industry_id, source_column, target_column, status, project_id, created_at, updated_at)
VALUES ('lt_packaging_solution_supports_high_bandwidth_memory', '封装方案适配HBM', 'packaging_solution', 'high_bandwidth_memory', 'M:N', '能力适配', '表达CoWoS-L承载GPU die与HBM3E堆栈互连的能力。', NULL, NULL, NULL, 'active', 'project_1780997325389', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE name=VALUES(name), source_object_id=VALUES(source_object_id), target_object_id=VALUES(target_object_id), link_category=VALUES(link_category), description=VALUES(description), status='active', updated_at=CURRENT_TIMESTAMP;

INSERT INTO link_types (id, name, source_object_id, target_object_id, cardinality, link_category, description, industry_id, source_column, target_column, status, project_id, created_at, updated_at)
VALUES ('lt_high_bandwidth_memory_adopts_hbm_generation', 'HBM采用HBM世代', 'high_bandwidth_memory', 'hbm_generation', 'M:N', '技术关联', '将HBM3E产品实例与HBM3E技术世代连接。', NULL, NULL, NULL, 'active', 'project_1780997325389', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE name=VALUES(name), source_object_id=VALUES(source_object_id), target_object_id=VALUES(target_object_id), link_category=VALUES(link_category), description=VALUES(description), status='active', updated_at=CURRENT_TIMESTAMP;

-- Link instances for link_instance_data
INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_training_accelerator_relation_ai_server_application', 'obj_training_accelerator_gb200', 'obj_app_ai_server_training'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_training_accelerator_relation_ai_server_application' AND source_instance_id='obj_training_accelerator_gb200' AND target_instance_id='obj_app_ai_server_training'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_graphics_processing_unit_relation_ai_server_application', 'obj_gpu_nvidia_b200', 'obj_app_ai_server_training'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_graphics_processing_unit_relation_ai_server_application' AND source_instance_id='obj_gpu_nvidia_b200' AND target_instance_id='obj_app_ai_server_training'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_graphics_processing_unit_adopts_gpu_architecture_generation', 'obj_gpu_nvidia_b200', 'obj_gpu_arch_blackwell'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_graphics_processing_unit_adopts_gpu_architecture_generation' AND source_instance_id='obj_gpu_nvidia_b200' AND target_instance_id='obj_gpu_arch_blackwell'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_training_accelerator_adopts_gpu_architecture_generation', 'obj_training_accelerator_gb200', 'obj_gpu_arch_blackwell'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_training_accelerator_adopts_gpu_architecture_generation' AND source_instance_id='obj_training_accelerator_gb200' AND target_instance_id='obj_gpu_arch_blackwell'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_gpu_architecture_generation_drives_advanced_packaging_technology', 'obj_gpu_arch_blackwell', 'obj_adv_packaging_chiplet_multi_die'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_gpu_architecture_generation_drives_advanced_packaging_technology' AND source_instance_id='obj_gpu_arch_blackwell' AND target_instance_id='obj_adv_packaging_chiplet_multi_die'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_packaging_technology_generation_relation_advanced_packaging_technology', 'obj_packaging_generation_2_5d', 'obj_adv_packaging_cowos'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_packaging_technology_generation_relation_advanced_packaging_technology' AND source_instance_id='obj_packaging_generation_2_5d' AND target_instance_id='obj_adv_packaging_cowos'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_advanced_packaging_technology_corresponds_to_packaging_solution', 'obj_adv_packaging_cowos', 'obj_packaging_solution_tsmc_cowos_l'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_advanced_packaging_technology_corresponds_to_packaging_solution' AND source_instance_id='obj_adv_packaging_cowos' AND target_instance_id='obj_packaging_solution_tsmc_cowos_l'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_graphics_processing_unit_adopts_packaging_solution', 'obj_gpu_nvidia_b200', 'obj_packaging_solution_tsmc_cowos_l'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_graphics_processing_unit_adopts_packaging_solution' AND source_instance_id='obj_gpu_nvidia_b200' AND target_instance_id='obj_packaging_solution_tsmc_cowos_l'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_packaging_solution_supports_high_bandwidth_memory', 'obj_packaging_solution_tsmc_cowos_l', 'obj_hbm_hbm3e_generic'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_packaging_solution_supports_high_bandwidth_memory' AND source_instance_id='obj_packaging_solution_tsmc_cowos_l' AND target_instance_id='obj_hbm_hbm3e_generic'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_high_bandwidth_memory_adopts_hbm_generation', 'obj_hbm_skhynix_hbm3e', 'obj_hbm_generation_hbm3e'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_high_bandwidth_memory_adopts_hbm_generation' AND source_instance_id='obj_hbm_skhynix_hbm3e' AND target_instance_id='obj_hbm_generation_hbm3e'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_high_bandwidth_memory_supplies_to_graphics_processing_unit', 'obj_hbm_skhynix_hbm3e', 'obj_gpu_nvidia_b200'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_high_bandwidth_memory_supplies_to_graphics_processing_unit' AND source_instance_id='obj_hbm_skhynix_hbm3e' AND target_instance_id='obj_gpu_nvidia_b200'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_high_bandwidth_memory_supplies_to_graphics_processing_unit', 'obj_hbm_micron_hbm3e', 'obj_gpu_nvidia_b200'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_high_bandwidth_memory_supplies_to_graphics_processing_unit' AND source_instance_id='obj_hbm_micron_hbm3e' AND target_instance_id='obj_gpu_nvidia_b200'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_company_produces_for_assembly_test_service', 'obj_company_tsmc', 'obj_service_tsmc_cowos'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_company_produces_for_assembly_test_service' AND source_instance_id='obj_company_tsmc' AND target_instance_id='obj_service_tsmc_cowos'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_assembly_test_service_supports_capability_of_graphics_processing_unit', 'obj_service_tsmc_cowos', 'obj_gpu_nvidia_b200'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_assembly_test_service_supports_capability_of_graphics_processing_unit' AND source_instance_id='obj_service_tsmc_cowos' AND target_instance_id='obj_gpu_nvidia_b200'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_backend_facility_relation_company', 'obj_facility_tsmc_ap6', 'obj_company_tsmc'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_backend_facility_relation_company' AND source_instance_id='obj_facility_tsmc_ap6' AND target_instance_id='obj_company_tsmc'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_backend_facility_produces_for_assembly_test_service', 'obj_facility_tsmc_ap6', 'obj_service_tsmc_cowos'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_backend_facility_produces_for_assembly_test_service' AND source_instance_id='obj_facility_tsmc_ap6' AND target_instance_id='obj_service_tsmc_cowos'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_abf_substrate_supplies_to_graphics_processing_unit', 'obj_abf_substrate', 'obj_gpu_nvidia_b200'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_abf_substrate_supplies_to_graphics_processing_unit' AND source_instance_id='obj_abf_substrate' AND target_instance_id='obj_gpu_nvidia_b200'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_company_produces_for_abf_substrate', 'obj_company_ibiden', 'obj_abf_substrate'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_company_produces_for_abf_substrate' AND source_instance_id='obj_company_ibiden' AND target_instance_id='obj_abf_substrate'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_company_produces_for_abf_substrate', 'obj_company_unimicron', 'obj_abf_substrate'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_company_produces_for_abf_substrate' AND source_instance_id='obj_company_unimicron' AND target_instance_id='obj_abf_substrate'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_company_produces_for_abf_substrate', 'obj_company_shinko', 'obj_abf_substrate'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_company_produces_for_abf_substrate' AND source_instance_id='obj_company_shinko' AND target_instance_id='obj_abf_substrate'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_flip_chip_bonding_equipment_supports_capability_of_assembly_test_service', 'obj_equipment_flip_chip_bonder', 'obj_service_tsmc_cowos'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_flip_chip_bonding_equipment_supports_capability_of_assembly_test_service' AND source_instance_id='obj_equipment_flip_chip_bonder' AND target_instance_id='obj_service_tsmc_cowos'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_hybrid_bonding_equipment_supports_capability_of_assembly_test_service', 'obj_equipment_hybrid_bonder', 'obj_service_tsmc_cowos'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_hybrid_bonding_equipment_supports_capability_of_assembly_test_service' AND source_instance_id='obj_equipment_hybrid_bonder' AND target_instance_id='obj_service_tsmc_cowos'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_wafer_thinning_equipment_supports_capability_of_assembly_test_service', 'obj_equipment_wafer_thinning', 'obj_service_tsmc_cowos'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_wafer_thinning_equipment_supports_capability_of_assembly_test_service' AND source_instance_id='obj_equipment_wafer_thinning' AND target_instance_id='obj_service_tsmc_cowos'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_capital_expenditure_measures_for_assembly_test_service', 'obj_metric_tsmc_adv_packaging_capex', 'obj_service_tsmc_cowos'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_capital_expenditure_measures_for_assembly_test_service' AND source_instance_id='obj_metric_tsmc_adv_packaging_capex' AND target_instance_id='obj_service_tsmc_cowos'
);

INSERT INTO link_instance_data (link_type_id, source_instance_id, target_instance_id)
SELECT 'lt_capital_expenditure_measures_for_backend_facility', 'obj_metric_tsmc_adv_packaging_capex', 'obj_facility_tsmc_ap6'
WHERE NOT EXISTS (
  SELECT 1 FROM link_instance_data
  WHERE link_type_id='lt_capital_expenditure_measures_for_backend_facility' AND source_instance_id='obj_metric_tsmc_adv_packaging_capex' AND target_instance_id='obj_facility_tsmc_ap6'
);


SET FOREIGN_KEY_CHECKS=1;
